CLASS_NAMES: ['Car', 'Pedestrian', 'Cyclist']

DATA_CONFIG: 
    POINT_CLOUD_RANGE: [0, -39.68, -3, 69.12, 39.68, 1]
    POINT_FEATURE_ENCODING: {
      encoding_type: absolute_coordinates_encoding,
      used_feature_list: ['x', 'y', 'z', 'intensity'],
      src_feature_list: ['x', 'y', 'z', 'intensity'],
    }
    PREVIEW_CHANNEL: ["detector"]
    DATA_PROCESSOR:
        detector:
          # - NAME: sample_cache
          #   FILENAME: ".\\dataset\\"
          #   SAMPLE_FREQUENCY: 200

          - NAME: mask_points_by_range
            POINT_CLOUD_RANGE: [0, -39.68, -3, 69.12, 39.68, 1]

          # - NAME: raw_data_remain
          
          - NAME: transform_points_to_voxels
            VOXEL_SIZE: [0.16, 0.16, 4]
            MAX_POINTS_PER_VOXEL: 32
            MAX_NUMBER_OF_VOXELS: {
              'train': 16000,
              'test': 40000
            }

        # cross_sensor:
        #   - NAME: utils.mods.pre_pocessing.robo3d.cross_sensor_process
        #     EXT_MODULE: True
        #     NUM_BEAM_TO_DROP: 32

        # simulate_fog:
        #   - NAME: utils.mods.pre_pocessing.robo3d.simulate_fog
        #     EXT_MODULE: True
        #     INTENSITY: soft
        #   # intensity:[soft, hard]
        #     GAIN: False
        #     INTE_NAME: integral_lookup_tables_seg_light_0.008beta
        #     NOISE: 10
        #     BETA: 0.2
        #     NOISE_VARIANT: v1
          # light:[0.04, 0.04, 0.04]; moderate:[0.08, 0.08, 0.08]; heavy:[0.10, 0.10, 0.10]  
          # beta = [0.008, 0.05, 0.2]

        # motion_blur:
        #   - NAME: utils.mods.pre_pocessing.robo3d.motion_blur
        #     EXT_MODULE: True
        #     TRANS_STD: [0.10, 0.10, 0.10]
          # light:[0.04, 0.04, 0.04]; moderate:[0.08, 0.08, 0.08]; heavy:[0.10, 0.10, 0.10]   


MODEL:
    NAME: PointPillar
    POST_PROCESSING:
        RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
        SCORE_THRESH: 0.1
        OUTPUT_RAW_SCORE: False

        EVAL_METRIC: kitti

        NMS_CONFIG:
            MULTI_CLASSES_NMS: False
            NMS_TYPE: nms_gpu
            NMS_THRESH: 0.01
            NMS_PRE_MAXSIZE: 4096
            NMS_POST_MAXSIZE: 500
